-- Vegetable prices table for storing recent prices
CREATE TABLE vegetable_prices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users NOT NULL,
  veg_name TEXT NOT NULL,
  last_price DECIMAL(10,2) DEFAULT 0,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  UNIQUE(user_id, veg_name)
);

-- Enable RLS
ALTER TABLE vegetable_prices ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage own veg prices" ON vegetable_prices 
FOR ALL USING (auth.uid() = user_id) 
WITH CHECK (auth.uid() = user_id);
