name: Supabase Keep-Alive

on:
  schedule:
    - cron: '0 0 * * *' # প্রতিদিন মাঝরাতে (UTC) রান হবে
  workflow_dispatch: # এটি যোগ করলে আপনি ম্যানুয়ালি রান করতে পারবেন

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to Supabase
        run: |
          curl --request GET \
            --url 'https://bemicqizbasldpdwglyu.supabase.co/rest/v1/activity_logs?select=*&limit=1' \
            --header 'apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlbWljcWl6YmFzbGRwZHdnbHl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzMDY1ODUsImV4cCI6MjA4NTg4MjU4NX0.PudPE1RG_BW-Z6kxBYn7TtpPalpVAE9osCCQGyqUaeI' \
            --header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlbWljcWl6YmFzbGRwZHdnbHl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzMDY1ODUsImV4cCI6MjA4NTg4MjU4NX0.PudPE1RG_BW-Z6kxBYn7TtpPalpVAE9osCCQGyqUaeI'
